author: Arthri
name: Check End-of-Line Sequences
description: "Lints text files' end-of-line sequences."

inputs:
  default-eol:
    default: lf
    description: Specifies the default end-of-line sequence. The supported values are "lf"(default), "crlf", and "mixed".
    required: false

runs:
  using: composite
  steps:
    - name: Check End-of-Line Sequences
      shell: bash
      env:
        DEFAULT_EOL: ${{ inputs.default-eol }}
      run: |
        exit_code=0

        while IFS= read line; do
          if [[ $line =~ ^i/([^ ]*)\ +w/[^\ ]*\ +attr/[^$'\t']+$'\t'(.+)$ ]] ; then
            index_eol=${BASH_REMATCH[1]}
            if [ "$index_eol" != $DEFAULT_EOL ] && [ "$index_eol" != 'none' ] ; then
              echo "${BASH_REMATCH[2]}:"$'\t'"End-of-line sequence in index($index_eol) must be LF."
              exit_code=1
            fi
          else
            echo 'Unable to match '"$line"
            exit_code=1
          fi
        done < <(git ls-files --eol)

        exit $exit_code
