name: New Reusable Workflow
run-name: New Reusable Workflow

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  reusable-workflow:
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
      - run: echo Hello, World!
